### ISSUE TITLE
Local login credentials for runner

### ISSUE THREAD

**Issue by rakshith-ravi** [patr-cloud/patr#12]
The local UI for the runner should have credentials that are stored to access the local UI, along with a simple change password screen.

No need of workspaces or anything. Just a local login screen

**Comment by rakshith-ravi** [comment]
@argha-dot can you mention which PR fixed this?

**Comment by argha-dot** [comment]
[b0ccfa7](https://github.com/patr-cloud/patr/commit/b0ccfa7ca680707be20224a4c8c036863273f6b1) this commit adds a sign-up / login route, along some other stuff. There are further fixes for it down the line, but this is the first commit for it.
There are no UI changes specific to self-hosted in login/sign-up pages as of right now.

**Comment by rakshith-ravi** [comment]
Fixed in #42
