### ISSUE TITLE
Wrong alignment of deployment card

### ISSUE THREAD

**Issue by rakshith-ravi** [patr-cloud/patr#45]
<img width="371" alt="Screenshot 2024-09-20 at 5 13 12 AM" src="https://github.com/user-attachments/assets/dc82b17c-475d-4712-adcc-38cbaf793ec5">

Happens with the self-hosted runner on the `feature/self-hosted-frontend` branch

 - [x] Fix overflowing components
 - [x] Fix word wrapping for list item fields
 - [ ] #52

**Comment by argha-dot** [comment]
further issue: use ellipsis for the repository like with runner above
![image](https://github.com/user-attachments/assets/ff28cd4e-7001-4260-8110-d8398342e94f)

**Comment by rakshith-ravi** [comment]
We can also consider adding a tooltip to show the full value when it's ellipsized (I think we have a component for it)

**Comment by rakshith-ravi** [comment]
I think #50 caused a regression. Now I can't even open the manage deployment page

<img width="377" alt="Screenshot 2024-09-24 at 6 14 39 AM" src="https://github.com/user-attachments/assets/a87cc602-89af-40cc-991c-036e74e621d4">
