### ISSUE TITLE
Update deployment, not updating `deployment` table.

### ISSUE THREAD

**Issue by argha-dot** [patr-cloud/patr#47]
The `UpdateDeployment` API function in `runner` doesn't update the deployment table. The SQL query that does this is [here](https://github.com/argha-dot/patr/blob/feat/self-hosted-frontend/runners/common/src/routes/workspace/deployment/update_deployment.rs#L135-L143).

`UPDATE deployment SET name = COALESCE("test-dep", name) WHERE id = "<deployment-id>";` works in the SQLite shell, but the linked code doesn't do anything.

The request is being sent correctly and the types for `bind()` are correct as well.

**Comment by rakshith-ravi** [comment]
Fixed in #50
